### ISSUE TITLE
Overarching updates

### ISSUE THREAD

**Issue by Peter-Kedron** [HEGSRR/HEGSRR-Template#11]
**Short term modifications** 
- [x] Dublin core on top-level readme
- [x] Single instructions line about what to do if files are >100mb
- [x] Move metadata readme information into HEGSRR-Manual
- [x] Shift language away from R&R to research more broadly

**Medium term modifications**
- [x] Convert pre-analysis plan .docx into .tex and .md files, and move instructions into HEGSRR-Manual

**Comment by josephholler** [comment]
- top readme is good to go with compliance with Dublin Core.
- instructions about large files are in the manual. could add more about what to do if you accidentally commit one.
- at least copied all good advice from individual readme files into the manual. a last draft of this may go back to the template to make sure those are all still consistent, or largely remove instructions from the template & instead link to appropriate sections of the manual so that there is only one set of cohesive instructions in the Manual. Things get confusing if there are too many different sets of instructions.

**Comment by josephholler** [comment]
These are all set; for now let's work with just a markdown / rmarkdown version of analysis plan
